# -*- coding: utf-8 -*-
"""forecasting_hw1_postgres.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y51KhecGyKgrj4pK3E78PNaHyoAVf-mH
"""

!pip install psycopg2-binary sqlalchemy -q

import pandas as pd
from sqlalchemy import create_engine
from google.colab import files

engine = create_engine(
    "postgresql://neondb_owner:npg_Z1zt4NJgXCWQ@ep-delicate-salad-am6iykoi-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require"
)

print("Upload your 2009_2010.csv file when prompted...")
uploaded = files.upload()

filename = list(uploaded.keys())[0]
print(f"Reading {filename}... this may take a moment")

total = 0
for i, chunk in enumerate(pd.read_csv(filename, chunksize=5000, encoding='utf-8', on_bad_lines='skip')):
    chunk.columns = [c.strip() for c in chunk.columns]
    chunk.to_sql('year_2009_2010', engine, if_exists='replace' if i == 0 else 'append', index=False)
    total += len(chunk)
    print(f"  {total} rows uploaded...")

print(f"DONE! year_2009_2010 → {total} rows total")

print("Upload your 2010_2011.csv file when prompted...")
uploaded = files.upload()

filename = list(uploaded.keys())[0]
print(f"Reading {filename}... this may take a moment")

total = 0
for i, chunk in enumerate(pd.read_csv(filename, chunksize=5000, encoding='utf-8', on_bad_lines='skip')):
    chunk.columns = [c.strip() for c in chunk.columns]
    chunk.to_sql('year_2010_2011', engine, if_exists='replace' if i == 0 else 'append', index=False)
    total += len(chunk)
    print(f"  {total} rows uploaded...")

print(f"DONE! year_2010_2011 → {total} rows total")

